"""Generate the Recovery clinic app Word manual.

Uses python-docx to produce a docx with three audiences (patient / staff /
master) plus FAQ. Embeds the illustrations generated by
docs/generate-illustrations.py. The owner can edit any text or replace any
illustration with a real screenshot afterwards.
"""

from __future__ import annotations

import os
from docx import Document
from docx.shared import Cm, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

ROOT = "/home/user/--mochizuki"
ILLUS = os.path.join(ROOT, "docs/illustrations")
LOGO = os.path.join(ROOT, "clinic-app/public/logo/logo-full.png")
LOGO_MARK = os.path.join(ROOT, "clinic-app/public/logo/logo-mark.png")
OUTPUT = os.path.join(ROOT, "docs/recovery-app-manual.docx")

ACCENT_HEX = RGBColor(0xE0, 0xAE, 0x08)  # accent-600
INK_900 = RGBColor(0x0F, 0x11, 0x15)
INK_500 = RGBColor(0x5B, 0x62, 0x70)
ROSE = RGBColor(0xDC, 0x26, 0x26)


# --- Helpers --------------------------------------------------------------


def add_heading(doc, text: str, level: int = 1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = INK_900
    return h


def add_section_label(doc, text: str, color=ACCENT_HEX):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(9)
    r.font.bold = True
    r.font.color.rgb = color
    return p


def add_paragraph(doc, text: str, size: int = 11, bold: bool = False, color=None):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.size = Pt(size)
    if bold:
        r.font.bold = True
    if color:
        r.font.color.rgb = color
    return p


def add_bullets(doc, items: list[str]):
    for it in items:
        p = doc.add_paragraph(it, style="List Bullet")
        for r in p.runs:
            r.font.size = Pt(11)


def add_numbered(doc, items: list[str]):
    for it in items:
        p = doc.add_paragraph(it, style="List Number")
        for r in p.runs:
            r.font.size = Pt(11)


def add_image(doc, path: str, width_cm: float = 14, caption: str | None = None):
    if not os.path.exists(path):
        # Fallback: visible placeholder text so the manual still renders.
        p = doc.add_paragraph()
        r = p.add_run(f"[ 図: {os.path.basename(path)} が見つかりません ]")
        r.font.italic = True
        r.font.color.rgb = INK_500
        return
    doc.add_picture(path, width=Cm(width_cm))
    last = doc.paragraphs[-1]
    last.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if caption:
        cap = doc.add_paragraph()
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        cr = cap.add_run(f"図. {caption}")
        cr.font.size = Pt(9)
        cr.font.italic = True
        cr.font.color.rgb = INK_500


def add_callout(doc, title: str, body: str, tone: str = "info"):
    """Boxed callout drawn as a 1-row table for visual contrast."""
    color_map = {
        "info": "FFFBE6",      # accent-50
        "warn": "FEF3C7",      # amber
        "danger": "FEE2E2",    # rose
    }
    table = doc.add_table(rows=1, cols=1)
    table.autofit = True
    cell = table.cell(0, 0)
    cell.vertical_alignment = WD_ALIGN_VERTICAL.TOP
    # Background colour
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), color_map.get(tone, color_map["info"]))
    tc_pr.append(shd)

    # Body
    cp = cell.paragraphs[0]
    tr = cp.add_run(title + "\n")
    tr.bold = True
    tr.font.size = Pt(11)
    br = cp.add_run(body)
    br.font.size = Pt(10)
    doc.add_paragraph()  # spacing


def page_break(doc):
    p = doc.add_paragraph()
    p.add_run().add_break(WD_BREAK.PAGE)


# --- Document building ----------------------------------------------------


def build_document() -> str:
    doc = Document()

    # Set default font to Noto Sans for Japanese support if available
    style = doc.styles["Normal"]
    style.font.name = "Yu Gothic"
    style.font.size = Pt(11)

    # === COVER ===
    if os.path.exists(LOGO):
        doc.add_picture(LOGO, width=Cm(8))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = title.add_run("リカバリー鍼灸院 アプリ")
    tr.font.size = Pt(28)
    tr.font.bold = True
    tr.font.color.rgb = INK_900

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = subtitle.add_run("取扱説明書")
    sr.font.size = Pt(20)
    sr.font.color.rgb = ACCENT_HEX
    sr.font.bold = True

    doc.add_paragraph()
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    ir = info.add_run("Karada Compass / 体質診断 + カルテ管理")
    ir.font.size = Pt(11)
    ir.font.color.rgb = INK_500

    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()
    issued = doc.add_paragraph()
    issued.alignment = WD_ALIGN_PARAGRAPH.CENTER
    er = issued.add_run("発行: リカバリー鍼灸院\n初版: 2026年4月")
    er.font.size = Pt(10)
    er.font.color.rgb = INK_500

    page_break(doc)

    # === TABLE OF CONTENTS (簡易) ===
    add_heading(doc, "目次", level=1)
    toc_items = [
        "はじめに",
        "第1部 患者さま向け（マイページ）",
        "  1.1 アプリへのアクセス方法",
        "  1.2 マイページの全体構成",
        "  1.3 今日の体調を記録する",
        "  1.4 来院予約する",
        "  1.5 カレンダーの使い方",
        "  1.6 体質診断結果を見る",
        "第2部 スタッフ向け（管理画面）",
        "  2.1 ログイン",
        "  2.2 患者一覧",
        "  2.3 患者の新規登録",
        "  2.4 体質診断を実施",
        "  2.5 来院記録",
        "  2.6 体調を分析する",
        "  2.7 患者情報の編集",
        "  2.8 マイページQRコードの印刷",
        "第3部 院長(Master)向け",
        "  3.1 Masterの権限",
        "  3.2 院間移籍の操作",
        "  3.3 患者の削除",
        "  3.4 アカウント管理",
        "第4部 困ったとき",
        "  4.1 よくある質問",
        "  4.2 トラブル対処",
        "  4.3 用語集",
    ]
    for it in toc_items:
        p = doc.add_paragraph(it)
        p.paragraph_format.space_after = Pt(2)

    page_break(doc)

    # === はじめに ===
    add_heading(doc, "はじめに", level=1)
    add_paragraph(
        doc,
        "本書は「リカバリー鍼灸院 アプリ」の使い方をまとめた取扱説明書です。"
        "患者さま・スタッフ・院長 (Master) のそれぞれの立場から、"
        "アプリの基本操作と運用上のポイントをご案内します。",
    )
    add_paragraph(doc, "")
    add_paragraph(doc, "■ このアプリでできること", bold=True)
    add_bullets(
        doc,
        [
            "患者: 毎日の体調を簡単に記録 / 過去の診断結果と来院履歴を確認 / 来院予約",
            "スタッフ: 患者カルテの管理 / 体質診断の実施 / 体調分析",
            "院長: 両院の状態を俯瞰 / 患者の院間移籍 / 全体管理",
        ],
    )
    add_paragraph(doc, "")
    add_paragraph(doc, "■ 3つの役割と権限", bold=True)
    add_image(
        doc,
        os.path.join(ILLUS, "permissions-matrix.png"),
        width_cm=15,
        caption="役割ごとの操作権限",
    )

    page_break(doc)

    # ===========================================================
    # 第1部 患者さま向け
    # ===========================================================
    add_heading(doc, "第1部 患者さま向け", level=1)
    add_paragraph(
        doc,
        "患者さまがマイページを使って、毎日の体調を記録し、過去の診断結果や来院履歴を確認するための説明です。",
    )
    add_paragraph(doc, "")

    add_heading(doc, "1.1 アプリへのアクセス方法", level=2)
    add_section_label(doc, "INITIAL ACCESS")
    add_paragraph(
        doc,
        "院でお渡しする QR コードカードを読み取ると、自動でログイン画面が開きます。"
        "カルテ番号とお名前は入力済みなので、内容を確認して「マイページへ」を押すだけです。",
    )
    add_image(
        doc,
        os.path.join(ILLUS, "login-flow.png"),
        width_cm=15,
        caption="QR コードからのログインフロー",
    )

    add_paragraph(doc, "■ ホーム画面に追加する (推奨)", bold=True)
    add_paragraph(
        doc,
        "iPhone の Safari でアプリを開き、画面下の共有ボタンから「ホーム画面に追加」をタップすると、"
        "ホーム画面にリカバリー鍼灸院のアイコンが追加されます。次回からはアイコンをタップするだけでアプリが開きます。",
    )
    add_callout(
        doc,
        "💡 ポイント",
        "ホーム画面に追加後はネット接続が無くても、一度開いた画面はキャッシュから表示されます。",
    )

    add_heading(doc, "1.2 マイページの全体構成", level=2)
    add_paragraph(
        doc,
        "マイページは上から順に、操作ボタン → カレンダー → 体調の傾向、の構成です。",
    )
    add_image(
        doc,
        os.path.join(ILLUS, "mypage-overview.png"),
        width_cm=12,
        caption="マイページの全体構成 (イメージ)",
    )

    add_heading(doc, "1.3 今日の体調を記録する", level=2)
    add_paragraph(
        doc,
        "「＋ 今日の体調を記録する」ボタンをタップすると、6つのセクションがある記録フォームが開きます。"
        "すべて任意項目です。書ける範囲だけで十分です。",
    )
    add_image(
        doc,
        os.path.join(ILLUS, "log-form-sections.png"),
        width_cm=14,
        caption="記録フォームの6つのセクション",
    )

    add_paragraph(doc, "■ 各セクションの使い方", bold=True)
    add_bullets(
        doc,
        [
            "本日の調子: 5段階の絵文字から1つタップ (絶不調〜絶好調)",
            "痛み: 部位を選んで詳細パネルを開き、左右と強さ (1-5) を選択",
            "神経・自律神経: 該当する症状をタップで複数選択",
            "睡眠時間: 30分刻みのプルダウンから選択",
            "血圧: 任意。家庭血圧計の数値を入れると傾向がわかります",
            "メモ: その日の出来事や気づきを自由記述 (2000字まで)",
        ],
    )
    add_callout(
        doc,
        "✅ 30秒で書けるコツ",
        "最初は「気分」だけでも OK です。続けて記録することで、施術前後の比較やパターンが見えてきます。",
    )

    add_heading(doc, "1.4 来院予約する", level=2)
    add_paragraph(
        doc,
        "マイページ上部の黒いボタン「来院予約する」をタップすると、通っている院専用の予約サイトが新しいタブで開きます。",
    )
    add_callout(
        doc,
        "ℹ️ 院ごとに別の予約サイト",
        "あなたが通われている院の予約ページに自動で遷移します。"
        "もし「予約サイト URL が未設定です」と表示される場合は、院にお問い合わせください。",
    )

    add_heading(doc, "1.5 カレンダーの使い方", level=2)
    add_paragraph(
        doc,
        "カレンダーは過去の記録を一覧でき、日付をタップするとその日の詳細パネルが下に開きます。",
    )
    add_image(
        doc,
        os.path.join(ILLUS, "calendar-tap.png"),
        width_cm=15,
        caption="カレンダーの日付をタップで詳細パネル",
    )

    add_paragraph(doc, "■ ドット (●) の意味", bold=True)
    add_bullets(
        doc,
        [
            "🟡 黄色: 体質診断あり (院でスタッフが実施した日)",
            "🟢 緑: 体調記録あり (患者さまが記録した日)",
            "🔵 青: 来院記録あり",
        ],
    )

    add_paragraph(doc, "■ 詳細パネルでできること", bold=True)
    add_bullets(
        doc,
        [
            "体質診断あり: 「詳細を見る」で結果ページへ",
            "体調記録あり: 「編集」で編集ページへ",
            "来院記録あり: 「取り消す」で削除",
            "未記録の日: 「+ 体調を記録する」「+ 来院を記録する」でその場で追加",
        ],
    )

    add_heading(doc, "1.6 体質診断結果を見る", level=2)
    add_paragraph(
        doc,
        "体質診断はスタッフが院で実施します。診断後、マイページから過去の診断結果をいつでも振り返ることができます。",
    )
    add_paragraph(doc, "■ 結果画面で見られるもの", bold=True)
    add_bullets(
        doc,
        [
            "あなたのタイプ (神経過敏 / 循環不足 / 代謝低下 / バランス / 複合)",
            "体質スコア (0〜100、3軸の平均)",
            "3軸レーダーチャート (神経・循環・代謝)",
            "前回診断との変化 (2回目以降)",
            "改善アドバイス (睡眠・食事・運動・ストレス)",
        ],
    )
    add_callout(
        doc,
        "📊 数値の見方",
        "体質スコアは「数値が大きいほど良好」です。前回より上がっていれば改善傾向、下がっていれば一時的に乱れている可能性があります。",
    )

    page_break(doc)

    # ===========================================================
    # 第2部 スタッフ向け
    # ===========================================================
    add_heading(doc, "第2部 スタッフ向け", level=1)
    add_paragraph(
        doc,
        "院のスタッフが患者カルテを管理し、体質診断・記録閲覧・分析を行うための説明です。",
    )

    add_heading(doc, "2.1 ログイン", level=2)
    add_paragraph(
        doc,
        "管理画面のログインページで、各院の合言葉を入力してください。"
        "合言葉により所属する院が自動判定されます。",
    )
    add_callout(
        doc,
        "🔐 合言葉について",
        "合言葉は院ごとに3種類あります (Master / 長泉三島 / 裾野長泉)。"
        "誤って他院の合言葉でログインすると、その院の患者しか見えなくなります。",
        tone="warn",
    )

    add_heading(doc, "2.2 患者一覧", level=2)
    add_paragraph(
        doc,
        "ログイン直後に表示されるホーム画面です。検索とフィルターで絞り込みができます。",
    )
    add_paragraph(doc, "■ 主な機能", bold=True)
    add_bullets(
        doc,
        [
            "検索ボックス: カルテ番号 / 氏名 / ふりがなで絞り込み",
            "フィルター: すべて / 直近30日 / 60日以上未来院",
            "院長(Master)は両院の患者を見られ、店舗スタッフは自院のみ表示",
            "リスト各行をタップで患者詳細へ",
        ],
    )

    add_heading(doc, "2.3 患者の新規登録", level=2)
    add_paragraph(doc, "右上の「＋ 新規登録」ボタンから登録します。")
    add_paragraph(doc, "■ 入力項目", bold=True)
    add_bullets(
        doc,
        [
            "カルテ番号 (必須): 院ごとに自由な体系で OK",
            "氏名 (必須): 漢字で入力。患者ログインの照合にも使用",
            "ふりがな (任意): 検索の補助に",
            "生年月日 (任意): 誕生日カレンダーに使用",
            "通院院: 店舗スタッフは自動で自院、Master は選択可能",
            "メモ (任意): 既往歴・初診時の主訴など",
        ],
    )
    add_callout(
        doc,
        "📌 カルテ番号は院ごとに独立",
        "1号店と2号店で同じ番号 (例: A0001) を別の患者に使えます。"
        "重複チェックは同じ院内のみで行われます。",
    )

    add_heading(doc, "2.4 体質診断を実施", level=2)
    add_paragraph(
        doc,
        "患者詳細ページの「＋ 体質診断を実施」ボタンから問診画面に進みます。"
        "院のタブレットで操作するか、患者さま本人に画面を見せながら進めてください。",
    )
    add_paragraph(doc, "■ 診断の流れ", bold=True)
    add_numbered(
        doc,
        [
            "「＋ 体質診断を実施」をタップ",
            "15問の問診 (1問あたり10秒程度)",
            "結果画面で 3軸スコア + タイプを確認",
            "結果は自動的に患者のカルテに保存されます",
        ],
    )

    add_heading(doc, "2.5 来院記録", level=2)
    add_paragraph(
        doc,
        "来院日は2つの方法で記録できます。",
    )
    add_paragraph(doc, "■ 方法A: 患者詳細のカレンダーから 1日ずつ", bold=True)
    add_paragraph(
        doc,
        "カレンダーで日付をタップ → 表示される詳細パネルから「+ 来院を記録する」をタップ。"
        "間違えた場合は「取り消す」リンクで即削除できます。",
    )
    add_paragraph(doc, "■ 方法B: 来院記録ページから複数日まとめて", bold=True)
    add_paragraph(
        doc,
        "「📅 来院記録 (N)」ボタンから一括編集ページを開き、複数の日付をタップで選択 → 「保存する」で一気に反映。",
    )
    add_callout(
        doc,
        "🩺 院での運用ヒント",
        "施術後すぐに来院記録を残すと、患者本人が後でマイページから自身の通院履歴を確認できます。",
    )

    add_heading(doc, "2.6 体調を分析する", level=2)
    add_paragraph(
        doc,
        "「最近14日の体調」カードの下にある「📊 体調を分析する」ボタンから、期間別の分析ページへ進みます。",
    )
    add_image(
        doc,
        os.path.join(ILLUS, "admin-patient-layout.png"),
        width_cm=12,
        caption="患者詳細ページの構成",
    )
    add_paragraph(doc, "■ 分析ページの主要セクション", bold=True)
    add_bullets(
        doc,
        [
            "期間サマリー: 記録 / 来院 / 診断の件数",
            "体調の傾向: 気分・睡眠・血圧の平均と改善傾向",
            "痛みマップ: 体シルエットに不調部位をマッピング",
            "多かった不調: 頻度 + 強度ゲージで詳細表示",
            "推奨される施術カテゴリ: 自律神経 / 循環 / 局所 / 内臓 / 複合",
            "期間内の診断変化: 体質スコアの前後比較",
            "スタッフ共有用サマリー: コピーペーストでLINE共有可能なテキスト",
        ],
    )
    add_image(
        doc,
        os.path.join(ILLUS, "body-diagram.png"),
        width_cm=8,
        caption="痛みマップのイメージ",
    )

    add_paragraph(doc, "■ 期間プリセット", bold=True)
    add_bullets(
        doc,
        [
            "直近1週間 / 2週間 / 30日",
            "前回来院日から (来院前後の変化を見たい時)",
            "カスタム指定 (任意の from-to)",
        ],
    )
    add_callout(
        doc,
        "💬 スタッフ間の情報共有",
        "「スタッフ共有用サマリー」のコピーボタンを使うと、その日の患者の状態を1行でまとめたテキストを LINE や院内ノートに貼り付けて共有できます。",
    )

    add_heading(doc, "2.7 患者情報の編集", level=2)
    add_paragraph(
        doc,
        "患者詳細ページ右上の「編集」リンクから、カルテ番号・氏名・通院院・メモなどを修正できます。"
        "通院院の変更 (移籍) は Master 権限のみ可能です。",
    )

    add_heading(doc, "2.8 マイページ QR コードの印刷", level=2)
    add_paragraph(
        doc,
        "新規患者には、マイページに簡単にアクセスできる QR カードを発行できます。",
    )
    add_paragraph(doc, "■ 手順", bold=True)
    add_numbered(
        doc,
        [
            "患者詳細ページの「マイページ QR コード」を展開",
            "「印刷用カードを開く」をクリック",
            "ブラウザの印刷機能で A6 サイズのウェルカムカードを印刷",
            "患者さまに手渡し",
        ],
    )

    page_break(doc)

    # ===========================================================
    # 第3部 院長(Master)向け
    # ===========================================================
    add_heading(doc, "第3部 院長 (Master) 向け", level=1)
    add_paragraph(
        doc,
        "院長 (Master) は両院の全患者を横断的に管理し、店舗スタッフでは行えない院間移籍や患者削除を実施できます。",
    )

    add_heading(doc, "3.1 Masterの権限", level=2)
    add_image(
        doc,
        os.path.join(ILLUS, "permissions-matrix.png"),
        width_cm=15,
        caption="Master と店舗スタッフの権限比較",
    )
    add_paragraph(doc, "■ Master だけができる操作", bold=True)
    add_bullets(
        doc,
        [
            "両院の患者を横断的に閲覧・編集",
            "未割り当て (clinic_id 未設定) の患者の閲覧",
            "患者の院間移籍 (clinic_id の変更)",
            "患者の削除 (記録もカスケード削除)",
            "ダッシュボードで両院合算の数値を確認",
        ],
    )

    add_heading(doc, "3.2 院間移籍の操作", level=2)
    add_paragraph(
        doc,
        "患者の通院院を変更する操作です。患者本人が引っ越し等で通院院を変更した時に使います。",
    )
    add_paragraph(doc, "■ 手順", bold=True)
    add_numbered(
        doc,
        [
            "Master でログイン",
            "対象の患者詳細ページを開く",
            "右上「編集」をタップ",
            "「通っている院」のセレクターから新しい院を選ぶ",
            "「保存する」をタップ",
        ],
    )
    add_callout(
        doc,
        "⚠️ 移籍後の見え方",
        "移籍した患者は、移籍先の院のスタッフのみが閲覧・編集できるようになります。"
        "過去の記録 (体質診断・体調記録・来院) はすべて引き継がれます。",
        tone="warn",
    )

    add_heading(doc, "3.3 患者の削除", level=2)
    add_paragraph(
        doc,
        "誤登録などで患者を完全削除する操作です。元に戻せません。",
    )
    add_paragraph(doc, "■ 手順", bold=True)
    add_numbered(
        doc,
        [
            "Master でログイン",
            "対象の患者詳細ページ → 「編集」",
            "ページ最下部の「DANGER ZONE」までスクロール",
            "「この患者を削除」をタップ",
            "確認ダイアログで「OK」",
        ],
    )
    add_callout(
        doc,
        "⛔ 注意",
        "削除すると、その患者の体質診断・体調記録・来院記録もすべて連鎖的に削除されます。"
        "復旧は不可能です。本当に必要な操作か必ず確認してください。",
        tone="danger",
    )

    add_heading(doc, "3.4 アカウント管理", level=2)
    add_paragraph(
        doc,
        "ログインに使う合言葉は環境変数 (Vercel) で管理されています。"
        "院のスタッフが変わった時などに、Master が新しい合言葉を設定する必要があります。",
    )
    add_paragraph(doc, "■ 合言葉の変更手順", bold=True)
    add_numbered(
        doc,
        [
            "Vercel ダッシュボードにログイン",
            "プロジェクト「mochizuki」→ Settings → Environment Variables",
            "対象の合言葉を編集 (ADMIN_PASSWORD_MASTER / _MAIN / _BRANCH)",
            "Save",
            "Deployments タブから「Redeploy」",
        ],
    )
    add_callout(
        doc,
        "🔑 合言葉の3種類",
        "ADMIN_PASSWORD_MASTER (院長用) / ADMIN_PASSWORD_MAIN (長泉三島) / "
        "ADMIN_PASSWORD_BRANCH (裾野長泉)。各院で別の合言葉を設定してください。",
    )

    page_break(doc)

    # ===========================================================
    # 第4部 困ったとき
    # ===========================================================
    add_heading(doc, "第4部 困ったとき", level=1)

    add_heading(doc, "4.1 よくある質問", level=2)

    faqs = [
        (
            "Q. 患者さまがログインできないと言っています",
            "A. カルテ番号と氏名 (漢字含めて完全一致) を確認してください。"
            "登録時にスペースの有無や漢字の表記が違うと一致しません。"
            "編集画面で氏名を修正できます。",
        ),
        (
            "Q. アプリの動きが遅いです",
            "A. しばらく使っていない時に最初の表示が遅くなる場合があります "
            "(コールドスタート)。気になる場合は Vercel Pro へのアップグレードで改善できます。",
        ),
        (
            "Q. 1号店と2号店でカルテ番号が同じ患者がいます",
            "A. 院ごとにカルテ番号は独立しているので、別人として登録できます。"
            "両院に同じ番号の患者がいても問題ありません。",
        ),
        (
            "Q. 患者さまが他院のデータを見られないように設定されていますか?",
            "A. 患者は自分のデータのみ見られます。スタッフは自院の患者のみ。"
            "Master のみ両院横断で見られます。URL を直打ちしても他院の患者は見られません。",
        ),
        (
            "Q. 来院記録を間違えて入れてしまいました",
            "A. 患者詳細のカレンダーで該当日をタップ、または「📅 来院記録」"
            "から一括編集ページで該当日のチェックを外して保存してください。",
        ),
        (
            "Q. 体質診断の結果は患者さまも見られますか?",
            "A. はい。患者がマイページから過去の診断結果と推移をいつでも確認できます。"
            "ただし「施術メモ (スタッフ専用)」は患者には表示されません。",
        ),
        (
            "Q. 推奨施術カテゴリは何を基準に判定していますか?",
            "A. 過去の体調記録から「頻出する症状や痛み」を集計し、自律神経・"
            "循環・局所トリガー・内臓 / 代謝のいずれかに分類しています。"
            "目安として活用し、最終判断は施術者が行ってください。",
        ),
    ]
    for q, a in faqs:
        add_paragraph(doc, q, bold=True)
        add_paragraph(doc, a)
        doc.add_paragraph()

    add_heading(doc, "4.2 トラブル対処", level=2)
    add_paragraph(doc, "■ 画面が真っ白になった / エラーが出た", bold=True)
    add_numbered(
        doc,
        [
            "ブラウザを完全リロード (PC: Ctrl+Shift+R / iPhone: 履歴削除)",
            "それでもダメなら、別のブラウザで試す",
            "ログアウトして再ログイン",
            "改善しない場合は開発担当に画面のスクリーンショットを共有",
        ],
    )

    add_paragraph(doc, "■ 来院予約のリンクが開かない", bold=True)
    add_paragraph(
        doc,
        "Vercel の環境変数 (NEXT_PUBLIC_CLINIC_*_RESERVATION_URL) が設定されていない可能性があります。"
        "Master が環境変数を確認し、有効な URL を設定してください。",
    )

    add_paragraph(doc, "■ 合言葉を忘れた", bold=True)
    add_paragraph(
        doc,
        "Master が Vercel ダッシュボードから合言葉を再設定できます。"
        "再発行後、必ず関係スタッフに新しい合言葉を共有してください。",
    )

    add_heading(doc, "4.3 用語集", level=2)
    glossary = [
        ("カルテ番号", "院が患者ごとに付与する識別番号。院ごとに独立。"),
        ("体質スコア", "3軸 (神経・循環・代謝) の平均値。0〜100で、高いほど良好。"),
        (
            "3軸",
            "神経軸 (自律神経の安定度) / 循環軸 (末梢循環) / 代謝軸 (エネルギー回収)。",
        ),
        ("体質診断", "15問の問診で 3軸スコア + タイプを判定する院内オペレーション。"),
        ("体調記録 (Daily Log)", "患者が日々入力する気分・痛み・症状・睡眠・血圧・メモ。"),
        ("来院記録", "通院した日。患者またはスタッフが記録できる。"),
        ("PWA", "Progressive Web App。Webアプリをスマホのホーム画面に追加してアプリのように使う仕組み。"),
        ("Master", "院長権限。両院横断で全データ操作可能。"),
        ("Vercel", "本アプリをホスティングしているクラウドサービス。"),
        ("Supabase", "本アプリのデータを保管しているデータベースサービス。"),
    ]
    for term, desc in glossary:
        p = doc.add_paragraph()
        r1 = p.add_run(term + ": ")
        r1.font.bold = True
        r2 = p.add_run(desc)
        r2.font.size = Pt(10)

    # === 末尾 ===
    page_break(doc)
    add_paragraph(doc, "")
    end = doc.add_paragraph()
    end.alignment = WD_ALIGN_PARAGRAPH.CENTER
    er = end.add_run("— 取扱説明書 おわり —")
    er.font.size = Pt(11)
    er.font.italic = True
    er.font.color.rgb = INK_500

    doc.add_paragraph()
    foot = doc.add_paragraph()
    foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fr = foot.add_run(
        "本書はアプリ仕様変更時に随時改訂されます。\n最新版はリポジトリ docs/recovery-app-manual.docx を参照してください。"
    )
    fr.font.size = Pt(9)
    fr.font.color.rgb = INK_500

    doc.save(OUTPUT)
    return OUTPUT


if __name__ == "__main__":
    print("Generating manual…")
    out = build_document()
    print(f"Saved to: {out}")
    size_kb = os.path.getsize(out) / 1024
    print(f"Size: {size_kb:.1f} KB")
